export const CHANNEL_NAMES = {
    0: "Left Outer Main Beam",
    1: "Right Outer Main Beam",
    2: "Left Inner Main Beam",
    3: "Right Inner Main Beam",
    4: "Left Signature",
    5: "Right Signature",
    6: "Left Channel 4",
    7: "Right Channel 4",
    8: "Left Channel 5",
    9: "Right Channel 5",
    10: "Left Channel 6",
    11: "Right Channel 6",
    12: "Left Front Turn",
    13: "Right Front Turn",
    14: "Left Front Fog",
    15: "Right Front Fog",
    16: "Left Aux Park",
    17: "Right Aux Park",
    18: "Left Side Marker",
    19: "Right Side Marker",
    20: "Left Side Repeater",
    21: "Right Side Repeater",
    22: "Left Rear Turn",
    23: "Right Rear Turn",
    24: "Brake Lights",
    25: "Left Tail",
    26: "Right Tail",
    27: "Reverse Lights",
    28: "Rear Fog Lights",
    29: "License Plate Lights",
    30: "Left Falcon Door",
    31: "Right Falcon Door",
    32: "Left Front Door",
    33: "Right Front Door",
    34: "Left Mirror",
    35: "Right Mirror",
    36: "Left Front Window",
    37: "Right Front Window",
    38: "Left Rear Window",
    39: "Right Rear Window",
    40: "Liftgate",
    41: "Left Front Door Handle",
    42: "Right Front Door Handle",
    43: "Left Rear Door Handle",
    44: "Right Rear Door Handle",
    45: "Charge Port",
};

// Channels up to 47 are standard for Tesla
for (let i = 46; i < 48; i++) {
    if (!CHANNEL_NAMES[i]) CHANNEL_NAMES[i] = `Channel ${i}`;
}
